name: c2s
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1

  retrofit: ^4.0.1
  logger: ^2.4.0  # for logging purpose
  json_annotation: ^4.9.0
  dio: ^5.0.3
  shared_preferences: ^2.3.2
  intl: ^0.19.0
  image_picker: ^1.0.0
  pretty_dio_logger: ^1.4.0
  flutter_image_compress: ^2.3.0
  path_provider: ^2.1.4
  amplify_flutter: ^2.0.0
  amplify_auth_cognito: ^2.0.0
  amplify_authenticator: ^2.0.0
  aws_common: ^0.7.3
  amplify_storage_s3: ^2.4.1
  connectivity_plus: ^6.1.0


dev_dependencies:
  build_runner: ^2.3.3
  retrofit_generator: ^9.0.1
  json_serializable: ^6.6.2

  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - images/
    - assets/icons/

  fonts:
    - family: SF Pro Display
      fonts:
        - asset: fonts/sf_pro_display/sfprodisplayregular.otf
          weight: 400
        - asset: fonts/sf_pro_display/sfprodisplaymedium.otf
          weight: 600
        - asset: fonts/sf_pro_display/sfprodisplaybold.otf
          weight: 700

    - family: Roboto
      fonts:
        - asset: fonts/Roboto/Roboto-Regular.ttf